-- Enable the vector extension if not already enabled
create extension if not exists vector;

-- Create the documents table if it doesn't exist
create table if not exists public.documents (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    titulo text,
    documento text,
    nome_documento text,
    pagina integer,
    embedding vector(384),
    pdf_path text,
    titulo_secao text
);

-- Create an index for faster vector searches if it doesn't exist
create index if not exists documents_embedding_idx on public.documents using ivfflat (embedding vector_cosine_ops) with (lists = 100);

-- Drop the existing function if it exists
drop function if exists public.match_documents;

-- Create the match_documents function
create or replace function public.match_documents (
    query_embedding vector(384),
    match_threshold float,
    match_count int,
    offset_value int
)
returns table (
    id bigint,
    titulo text,
    documento text,
    nome_documento text,
    pagina integer,
    pdf_path text,
    titulo_secao text,
    similarity float
)
language plpgsql
as $$
begin
    return query
    select
        d.id,
        d.titulo,
        d.documento,
        d.nome_documento,
        d.pagina,
        d.pdf_path,
        d.titulo_secao,
        1 - (d.embedding <=> query_embedding) as similarity
    from public.documents d
    where 1 - (d.embedding <=> query_embedding) > match_threshold
    order by similarity desc
    limit match_count
    offset offset_value;
end;
$$;

-- Add permissions for the function
grant execute on function public.match_documents(vector(384), float, int, int) to anon, authenticated, service_role; 