import os
from typing import List, Dict, Any, Optional
from supabase import create_client, Client
from dotenv import load_dotenv
from .raptor_rag import RaptorRAG, ChunkNode

# Load environment variables
load_dotenv()

class RaptorSupabase:
    def __init__(self, supabase_url: Optional[str] = None, supabase_key: Optional[str] = None):
        """
        Initialize RaptorSupabase client.
        
        Args:
            supabase_url (str, optional): Supabase URL. If None, reads from SUPABASE_URL env var.
            supabase_key (str, optional): Supabase API key. If None, reads from SUPABASE_KEY env var.
        """
        # Get Supabase credentials from environment variables if not provided
        self.supabase_url = supabase_url or os.getenv("SUPABASE_URL")
        self.supabase_key = supabase_key or os.getenv("SUPABASE_KEY")
        
        if not self.supabase_url or not self.supabase_key:
            raise ValueError("Supabase URL and API key must be provided either as arguments or environment variables.")
        
        # Initialize Supabase client
        self.supabase: Client = create_client(self.supabase_url, self.supabase_key)
        
        # Initialize RAPTOR RAG
        self.raptor = RaptorRAG()
    
    def _store_tree_node(self, node: ChunkNode, document_id: str, parent_id: Optional[str] = None) -> str:
        """
        Store a tree node in Supabase.
        
        Args:
            node (ChunkNode): Node to store
            document_id (str): ID of the parent document
            parent_id (str, optional): ID of the parent node
            
        Returns:
            str: ID of the stored node
        """
        # Insert node into Supabase
        response = self.supabase.table("raptor_nodes").insert({
            "document_id": document_id,
            "parent_id": parent_id,
            "text": node.text,
            "embedding": node.embedding.tolist(),
            "level": node.level,
            "metadata": node.metadata
        }).execute()
        
        return response.data[0]["id"]
    
    def _store_tree(self, root: ChunkNode, document_id: str) -> None:
        """
        Store entire tree in Supabase.
        
        Args:
            root (ChunkNode): Root node of the tree
            document_id (str): ID of the parent document
        """
        def store_node(node: ChunkNode, parent_id: Optional[str] = None):
            # Store current node
            node_id = self._store_tree_node(node, document_id, parent_id)
            
            # Recursively store children
            for child in node.children:
                store_node(child, node_id)
        
        store_node(root)
    
    def store_document(self, text: str, metadata: Dict[str, Any] = None) -> str:
        """
        Process and store a document using RAPTOR.
        
        Args:
            text (str): Document text
            metadata (Dict[str, Any], optional): Additional document metadata
            
        Returns:
            str: ID of the stored document
        """
        # Process document with RAPTOR
        root = self.raptor.process_document(text)
        
        # Store document metadata
        doc_response = self.supabase.table("documents").insert({
            "text": text,
            "metadata": metadata or {}
        }).execute()
        
        document_id = doc_response.data[0]["id"]
        
        # Store RAPTOR tree
        self._store_tree(root, document_id)
        
        return document_id
    
    def search(self, query: str, top_k: int = 5) -> List[Dict[str, Any]]:
        """
        Search documents using RAPTOR.
        
        Args:
            query (str): Search query
            top_k (int): Number of top results to return
            
        Returns:
            List[Dict[str, Any]]: List of search results
        """
        # Generate query embedding
        query_embedding = self.raptor.model.encode(query)
        
        # Search using vector similarity
        response = self.supabase.rpc(
            'match_raptor_nodes',
            {
                'query_embedding': query_embedding.tolist(),
                'match_threshold': 0.5,
                'match_count': top_k
            }
        ).execute()
        
        return response.data
    
    def create_match_function(self):
        """
        Create the match_raptor_nodes function in Supabase.
        """
        sql = """
        -- Create the raptor_nodes table if it doesn't exist
        create table if not exists public.raptor_nodes (
            id bigint generated by default as identity primary key,
            created_at timestamp with time zone default timezone('utc'::text, now()) not null,
            document_id bigint references documents(id),
            parent_id bigint references raptor_nodes(id),
            text text,
            embedding vector(384),
            level integer,
            metadata jsonb
        );

        -- Create an index for faster vector searches
        create index if not exists raptor_nodes_embedding_idx 
        on public.raptor_nodes using ivfflat (embedding vector_cosine_ops) 
        with (lists = 100);

        -- Drop the existing function if it exists
        drop function if exists public.match_raptor_nodes;

        -- Create the match_raptor_nodes function
        create or replace function public.match_raptor_nodes (
            query_embedding vector(384),
            match_threshold float,
            match_count int
        )
        returns table (
            id bigint,
            document_id text,
            text text,
            level integer,
            metadata jsonb,
            similarity float
        )
        language plpgsql
        as $$
        begin
            return query
            select
                n.id,
                n.document_id,
                n.text,
                n.level,
                n.metadata,
                1 - (n.embedding <=> query_embedding) as similarity
            from public.raptor_nodes n
            where 1 - (n.embedding <=> query_embedding) > match_threshold
            order by similarity desc
            limit match_count;
        end;
        $$;

        -- Add permissions for the function
        grant execute on function public.match_raptor_nodes(vector(384), float, int) 
        to anon, authenticated, service_role;
        """
        
        try:
            # Execute the SQL using the REST API
            self.supabase.rpc('exec_sql', {'sql': sql}).execute()
            return "match_raptor_nodes function created successfully"
        except Exception as e:
            print(f"Error creating function: {e}")
            # Try alternative method if the first one fails
            try:
                self.supabase.table("raptor_nodes").select("*").limit(1).execute()
                return "Table exists, proceeding with existing function"
            except Exception as e2:
                raise Exception(f"Failed to create or verify function: {str(e2)}") 