chat_task:
  description: >
    Como professor universitário deves dar resposta a questão:
    {question} 
    Tomar como base o conhecimento fornecido:
    {know-how}
    Scores correspondente de similaridade: {scores}
  expected_output: >
    Crie uma resposta concisa e bem argumentada sobre a pergunta realizada e seu análise do relatório.
    Acrecentar que qualquer dúvida pode consultar a seu professor
    Fazer uma avaliação do score de similaridade dos dados fornecidos com a pergunta.
    Para baixo score responder
